### ISSUE TITLE
Document of CDW-spinup process

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/prairie-outpost-public#2]
Several purposes:
1. Facilitate intra-team communication about the best way we should proceed for the typical CDW project.
1. Blueprint when we spin up a project.  Following a list should reduce the number of round trips we have to do w/ investigators.
1. Communicate with outsiders how the process works
    * PIs
    * IT's security team
    * authorities (eg, IRB, governance board)

**Comment by wibeasley** [comment]
@zantry, @DavidBard, @mand9472,  will you please review this protocol?  
* Tell me what you think about the format.  (eg, will it be easy to us to follow each time?)
* Are there big sections I'm forgetting?
* Are there little, but important details I'm forgetting?

https://github.com/OuhscBbmc/prairie-outpost-public/blob/master/documentation/services/spinup-investigation.md

**Comment by zantry** [comment]
I've taken a look through and I can only think of two things that might be helpful for me, although I'm not certain where they would go.  The first would be contact information for those involved in each project and possibly someone designated as the primary contact person.  I assume every one has an OU email address, but it isn't always easy to find them in Outlook.  A phone number would be great too because sometimes it is simply easier to communicate over the phone instead of through email.  The second being any deadlines for the projects.  I don't know if that would be helpful for everyone else, but I've needed this information in the past and it would be awesome to have it saved in one place.

**Comment by wibeasley** [comment]
@thomasnwilson, I like @zantry's suggestion, and want to incorporate the [REDCap project tracker's info](https://bbmc.ouhsc.edu/redcap/redcap_v6.14.2/DataExport/index.php?pid=80&report_id=268).  

Do you have suggestions?  For instance, in [these three email responses from the investigator](https://github.com/OuhscBbmc/prairie-outpost-public/blob/master/documentation/services/spinup-investigation.md#establishconfirm-collaborator-accounts), what's the best way to for them to refer to their REDCap project tracker entry?

**Comment by wibeasley** [comment]
@zantry, I talked to Thomas and David, and everyone agrees that we should require every CDW project to have a new record in the [BBMC Project Tracker](https://bbmc.ouhsc.edu/redcap/redcap_v6.14.2/DataExport/index.php?pid=80&report_id=268).

It has fields like email. phone, and deadlines.  I'll modify the [LDAP email skeleton](https://github.com/OuhscBbmc/BbmcResources/blob/master/instructions/username.md) so it also asks for their `record_id` for Project Tracker.

Thanks for bringing that up.  Anything else you'd like to see?
